name = "marvinmenzerath"
description = "Mein Blog-Theme"
tags = ["blog"]
min_version = 0.1

[author]
	name = "Marvin Menzerath"
	twitter = "https://twitter.com/MarvinMenzerath"
	url = "https://github.com/MarvinMenzerath"
